version: '3.8'

services:
  app:
    container_name: uni_bot
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    networks:
      - app_network

  redis:
    image: redis:latest
    container_name: uni_redis
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    networks:
      - app_network

volumes:
  redis_data:

networks:
  app_network:
    driver: bridge
