version: '3.8'

services:
  app:
    container_name: uni_bot
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: uni_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

# Определяем volume для Redis
volumes:
  redis_data: